version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ww_subscription

  app:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/ww_subscription
      TELEGRAM_BOT_TOKEN: example_token